name: Bump version
on:
  workflow_dispatch:
    inputs: 
      ReleaseVersion:
        description: "Release version number"
        required: true
jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{inputs.ReleaseVersion}}
          prerelease: false
          draft : true
          title: v${{inputs.ReleaseVersion }}
          files: |
            LICENSE.txt
            *.jar
