name: Bump version
on:
  workflow_dispatch:
    inputs: 
      majorNumber:
        description: "major version number"
        required: true
      minorNumber:
        description: "minor version number"
        required: true
      buildNumber:
        description: "build version number"
        required: true
      releaseNotesLink:
        description: "release notes wiki page link"
        required: true
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
